### ISSUE TITLE
Improper use of count() on string

### ISSUE THREAD

**Issue by petersontubini** [smartystreets/smartystreets-php-sdk#10]
You can't use `count()` on PHP strings because they don't implement [Countable](http://php.net/manual/en/class.countable.php), you must use `strlen` or it'll throw an exception.

```
private function fieldIsMissing($field) {
    return $field == null || count($field) == 0;
}
```

**Comment by MouaYing** [comment]
@petersontubini - Thank you for bringing this to our attention. This has been fixed in commit `3a99142e5eda2a0952054ffcedfce26c3d0bf098`.
