### ISSUE TITLE
International Address could use Batch Service.

### ISSUE THREAD

**Issue by chriscalip** [smartystreets/smartystreets-php-sdk#13]
Just like US Address; International Address could use Batch Service.

**Comment by mdwhatcott** [comment]
The International Street API actually doesn't support batching via POST requests like the US Street API does, hence the design difference in the SDK. The International Street API only accepts individual lookups as separate GET requests. But I suppose we could expose a batch interface in the SDK just the same. Thanks for the suggestion @chriscalip.

- https://smartystreets.com/docs/cloud/international-street-api
- https://smartystreets.com/docs/cloud/us-street-api
