### ISSUE TITLE
getResult() returns array, not an object

### ISSUE THREAD

**Issue by brynnb** [smartystreets/smartystreets-php-sdk#19]
https://github.com/smartystreets/smartystreets-php-sdk/blob/617815c4e3a6a6267a24f16f70dd8026706bb587/examples/USExtractExample.php#L42

As far as I can tell, ` $result = $lookup->getResult();` returns an array. Which means `$result->getMetadata();` doesn't work and returns `Fatal error: Call to undefined method SmartyStreets\PhpSdk\US_Street\Lookup::getMetadata()`.

Obviously ` $addresses = $result->getAddresses();` has the same issue.

Am I doing something wrong, or is the example maybe outdated?

**Comment by DuncanBeutler** [comment]
Sorry for the delayed response @brynnb , we are unable to reproduce your error on the latest versions of the example and the SDK. Are you still having issues with this?
