### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by ftrotter** [smartystreets/smartystreets-php-sdk#2]
Thanks for the great service. Very happy long time user.

I love that there is a php class. But having already written code to use the API, I am going to want to get back an array of results that has the same structure as your json results, and I want to create requests with arrays too... instead of using getters and setters. 

Not very efficient for keeping code nice and short. 

It seems like your code supports some of these things.. but your examples do not seem to. Is there any way you can highlight some of the "more than one way to do things" that your library is capable of in your default code?

Thanks,
-FT

**Comment by MouaYing** [comment]
@ftrotter - Thanks for your input. We would love it if you could give us an example of how it would look to use our SDK the way you are describing. We want to make sure we understand what you mean.

**Comment by ftrotter** [comment]
Sorry never had time to get to this... using the command line tool now... closing for clarity..
