### ISSUE TITLE
Add status code to thrown exceptions

### ISSUE THREAD

**Issue by luisdeguzman** [smartystreets/smartystreets-php-sdk#20]
It would be nice if the `$response->getStatusCode()` was added to all the exceptions thrown in `src/StatusCodeSender.php` so we can get the code via `$ex->getCode()` when catching the exceptions.

**Comment by abbeynels** [comment]
This issue has been resolved and you can now access the status code of exceptions thrown in src/StatusCodeSender.php by using $ex->getCode(). Thank you for suggesting this!
