### ISSUE TITLE
Please do not return null as the fall through condition for Curl responses

### ISSUE THREAD

**Issue by alaskancode** [smartystreets/smartystreets-php-sdk#30]
This is in StatusCodeSender.php. The default condition is to return null if the Curl status code is not matched. I recently had an issue where Curl was failing because the CaCert wasn't set in php.ini (this is a pretty common problem). But your API just returns null...thus taking me hours to climb through your code figuring out where the issue was.

Instead of trying to match the Curl status code for a select number of conditions and then returning null, please return the curl error as the fall through condition per this method:
https://stackoverflow.com/questions/8227909/curl-exec-always-returns-false

    function send(Request $request) {
		
        $response = $this->inner->send($request);

        switch ($response->getStatusCode()) {
            case 200:
                return $response;
            case 400:
                throw new BadRequestException("Bad Request (Malformed Payload): A GET request lacked a street field or the request body of a POST request contained malformed JSON.");
            case 401:
                throw new BadCredentialsException("Unauthorized: The credentials were provided incorrectly or did not match any existing, active credentials.");
            case 402:
                throw new PaymentRequiredException("Payment Required: There is no active subscription for the account associated with the credentials submitted with the request.");
            case 413:
                throw new RequestEntityTooLargeException("Request Entity Too Large: The request body has exceeded the maximum size.");
            case 429:
                throw new TooManyRequestsException("When using public \"website key\" authentication, we restrict the number of requests coming from a given source over too short of a time.");
            case 500:
                throw new InternalServerErrorException("Internal Server Error.");
            case 503:
                throw new ServiceUnavailableException("Service Unavailable. Try again later.");
            default:
                return null;
        }
    }

**Comment by DuncanBeutler** [comment]
Thanks for using the SDK! This issue was resolved on version 3.1.0. The latest version is 4.16.2 which contains updates as well as new features that may be helpful and which should be backwards compatible for anything besides the International Street API.

**Comment by alaskancode** [comment]
Hmmm....I think I copied the composer require from an old code file that was using this API. Oops...my mistake.
		"smartystreets/phpsdk": "1.0.2"
