### ISSUE TITLE
Found one compatibiliy issue with PHP8.1

### ISSUE THREAD

**Issue by vinsaj9** [smartystreets/smartystreets-php-sdk#36]
PHP Fatal error:  During inheritance of JsonSerializable: Uncaught Exception: Deprecated Functionality: Return type of SmartyStreets\PhpSdk\US_Street\Lookup::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

I have fixed it by forking the repo here https://github.com/vinsaj9/smartystreets-php-sdk.

**Comment by abbeynels** [comment]
The incompatibility issue was updated with the #[\ReturnTypeWillChange] attribute in commit c23faac4. Thank you for bringing this to our attention!
