### ISSUE TITLE
Verify the same address in the official website tool, but fail in the SDK

### ISSUE THREAD

**Issue by sam-sh0** [smartystreets/smartystreets-php-sdk#43]
Example，
Address： 9880 Polecat, Kingston, OK, 73439

website tool Results:
![image](https://github.com/smartystreets/smartystreets-php-sdk/assets/94431759/83ec1334-4743-41fa-bf05-e2cc9eb60936)

SDK :
Request params:
  ###   
    [street] => 9880 Polecat
    [street2] =>
    [city] => Kingston
    [state] => OK
    [zipcode] => 73439
    [match] => enhanced
    [candidates] => 4

Response:
###  
    [inputId] => 
    [inputIndex] => 0
    [candidateIndex] => 0
    [addressee] =>
    [deliveryLine1] => 9880 Polecat
    [deliveryLine2] =>
    [deliveryPointBarcode] => 734395600
    [lastLine] => Kingston OK 73439-5600
    [smartyKey] =>
    ...  ...  ... ... ... ...
    [analysis] => Array
        (
            [dpvMatchCode] => N
            [dpvFootnotes] => AAM3
            [cmra] =>
            [vacant] =>
            [noStat] =>
            [active] => Y
            [isEwsMatch] =>
            [footnotes] =>
            [lacsLinkCode] =>
            [lacsLinkIndicator] =>
            [isSuiteLinkMatch] =>
            [enhancedMatch] => non-postal-match
        )

**Comment by abbeynels** [comment]
Hi, that address is listed as valid in the SDK. The website demo states that the address you put in is a non-postal match, and contains the same result that is received in the SDK. If you are using the strict match strategy, the address will return not valid. You can read more about the different match types in our documentation [here](https://www.smarty.com/docs/cloud/us-street-api). Please let me know if you have any other questions.
