### ISSUE TITLE
Invalid PHPDoc comments in US_Street\Lookup

### ISSUE THREAD

**Issue by colonel-sanders** [smartystreets/smartystreets-php-sdk#5]
There are a couple of PHPDoc comments that are slightly off in \SmartyStreets\PhpSdk\US_Street\Lookup. This is causing trouble with static analysis tools, particularly Phan.

Pull request #4 submitted for consideration.

**Comment by MouaYing** [comment]
Pull request #4 has been merged. Thanks!
