### ISSUE TITLE
Credentials validations

### ISSUE THREAD

**Issue by Infernal15** [smartystreets/smartystreets-php-sdk#51]
Currently, there is no easy method in the SDK to validate Credentials without creating a request with address validation.
It would be nice if there was a simple way to validate credentials without creating unnecessary requests.

**Comment by RyanLCox1** [comment]
Credentials are validated only on the server side. Issuing invalid credentials will not count against lookups though. This is the purpose for a an http status code in the 400's. Only valid status codes in the 200s count against lookups.
