### ISSUE TITLE
Default configuration logs to STDOUT during failure backoff

### ISSUE THREAD

**Issue by colonel-sanders** [smartystreets/smartystreets-php-sdk#8]
The defaults within `ClientBuilder` can cause problems for PHP web apps. Unless the user overrides the default configuration by calling `setSender(...)` (or calls `retryAtMost(0)`) the generated clients use  a `RetrySender` wrapped around a `MyLogger` instance.

This default logger is problematic for web apps in that it writes to STDOUT. In most PHP web frameworks, this causes the logging output to be written out in the generated HTML of the current web request.

Ideally, the default would be to log these messages using `error_log` instead of `print`. However, the existing behavior may be something users are relying on. As a next best option, the builder interface should allow the logger to be (easily) overridden.

I've submitted a related PR: https://github.com/smartystreets/smartystreets-php-sdk/pull/7

**Comment by MouaYing** [comment]
Thank you, @colonel-sanders . We have merged your PR.
