### ISSUE TITLE
VERSION constant not namespaced

### ISSUE THREAD

**Issue by ryanhobrock** [smartystreets/smartystreets-php-sdk#9]
I just ran into an issue where the ```VERSION``` constant collided with the project SmartyStreets was being implemented in. Looking at the [source](https://github.com/smartystreets/smartystreets-php-sdk/blob/master/src/Version.php) it appears ```VERSION``` was meant to be namespaced but isn't. This should be implementable [two ways](https://stackoverflow.com/questions/18247726/php-define-constants-inside-namespace-clarification):

```php
<?php
namespace SmartyStreets\PhpSdk;
const VERSION = '4.3.2';
```

or

```php
<?php
namespace SmartyStreets\PhpSdk;
define(__NAMESPACE__ . '\VERSION', '4.3.2', false);
```

Since the minimum version for the SDK is PHP 5.6 the former might be preferable.

**Comment by MouaYing** [comment]
Thank you for bringing this to our attention, @ryanhobrock . This change has been included in version 4.4.0.
